services:
  backend:
    build: ./backend
    ports:
      - "80:80"
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /code
  # frontend:
  #   build: 
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./frontend
  #         target: /app