services:
  backend:
    build: ./backend
    ports:
      - "80:80"
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /code
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app